// ═══════════════════════════════════════════════════════════════════════════
// PLATFORM ALERTS — EnjoyBaja.com
// POST /api/alerts/notify
// Fires on every submission: MexicoRealEstate, USAMortgage, AuditDNARecovery
// Delivers: Email (sgarcia1911@gmail.com) + ntfy push (watch) + calendar entry
// ═══════════════════════════════════════════════════════════════════════════
// Save to: C:\AuditDNA\auditdna-realestate\backend\routes\platform-alerts.js
// Mount:   app.use('/api/alerts', require('./routes/platform-alerts'));

const express = require('express');
const router  = express.Router();
const fetch   = (() => { try { return require('node-fetch'); } catch(e) { return global.fetch; } })();

const OWNER_EMAIL  = process.env.OWNER_ALERT_EMAIL   || 'sgarcia1911@gmail.com';
const NTFY_TOPIC   = process.env.NTFY_TOPIC          || 'enjoybaja-owner-sg2026';
const NTFY_SERVER  = 'https://ntfy.sh';
const OWNER_PHONE  = '+18312513116'; // US cell — via ntfy to watch

// ── SOURCE LABELS ──────────────────────────────────────────────────────────
const SOURCE_LABEL = {
  'mexico-realestate':  'Mexico Real Estate',
  'usa-mortgage':       'USA Mortgage',
  'mexico-mortgage':    'Mexico Mortgage',
  'audit-recovery':     'Audit Recovery',
  'partner-loan':       'Coach Realty Partner',
  'agent-register':     'Agent Registration',
  'fsbo':               'FSBO Listing',
  'scout':              'Scout Property',
  'pre-approval':       'Pre-Approval Request',
  'inquiry':            'Property Inquiry',
};

// ── EMAIL HTML TEMPLATE ────────────────────────────────────────────────────
function buildEmail(data) {
  const label = SOURCE_LABEL[data.source] || data.source || 'Platform';
  const ts    = new Date().toLocaleString('en-US', { timeZone: 'America/Los_Angeles', hour12: true });
  const rows  = Object.entries(data)
    .filter(([k]) => !['source','timestamp'].includes(k))
    .map(([k,v]) => `<tr><td style="padding:6px 12px;color:#64748b;font-size:12px;text-transform:uppercase;letter-spacing:1px;width:140px">${k}</td><td style="padding:6px 12px;color:#0f172a;font-size:13px">${v||'—'}</td></tr>`)
    .join('');

  return {
    from:    `"EnjoyBaja Platform" <${process.env.GMAIL_USER || OWNER_EMAIL}>`,
    to:      OWNER_EMAIL,
    subject: `[${label}] New Submission — ${data.name || data.email || 'Unknown'} · ${ts}`,
    html: `
<div style="font-family:'Helvetica Neue',Arial,sans-serif;max-width:600px;margin:0 auto;background:#f8fafc">
  <div style="background:#0f172a;padding:20px 28px">
    <div style="font-size:10px;color:#cba658;letter-spacing:3px;margin-bottom:4px">ENJOYBAJA.COM — OWNER ALERT</div>
    <div style="font-size:20px;color:#f1f5f9;font-weight:300">${label}</div>
    <div style="font-size:12px;color:#475569;margin-top:4px">${ts}</div>
  </div>
  <div style="padding:0">
    <table style="width:100%;border-collapse:collapse">
      ${rows}
    </table>
  </div>
  <div style="padding:16px 28px;background:#f1f5f9;font-size:10px;color:#94a3b8;border-top:1px solid #e2e8f0">
    Saul Garcia · NMLS #337526 · EnjoyBaja.com · This alert was auto-generated by the EnjoyBaja platform.
  </div>
</div>`
  };
}

// ── NTFY PUSH (→ phone → smartwatch) ──────────────────────────────────────
async function sendNtfy(data) {
  const label = SOURCE_LABEL[data.source] || data.source;
  const title = `${label}: ${data.name || data.email || 'New Submission'}`;
  const body  = [
    data.email   ? `Email: ${data.email}`   : null,
    data.phone   ? `Phone: ${data.phone}`   : null,
    data.amount  ? `Amount: ${data.amount}` : null,
    data.type    ? `Type: ${data.type}`     : null,
    data.details ? data.details.slice(0,80)    : null,
  ].filter(Boolean).join(' · ');

  try {
    const fetchFn = typeof fetch === 'function' ? fetch : require('node-fetch');
    await fetchFn(`${NTFY_SERVER}/${NTFY_TOPIC}`, {
      method:  'POST',
      headers: {
        'Title':    title,
        'Priority': 'high',
        'Tags':     'bell,house',
        'Content-Type': 'text/plain',
      },
      body: body || 'New platform submission received.',
    });
    console.log('[ALERTS] ntfy push sent:', title);
  } catch(e) {
    console.warn('[ALERTS] ntfy failed (non-blocking):', e.message);
  }
}

// ── CALENDAR ENTRY ─────────────────────────────────────────────────────────
async function logCalendar(pool, data) {
  if(!pool) return;
  const label = SOURCE_LABEL[data.source] || data.source;
  try {
    // Check if platform_events table exists, create if not
    await pool.query(`
      CREATE TABLE IF NOT EXISTS platform_events (
        id          SERIAL PRIMARY KEY,
        source      TEXT,
        label       TEXT,
        name        TEXT,
        email       TEXT,
        phone       TEXT,
        amount      TEXT,
        type        TEXT,
        details     TEXT,
        created_at  TIMESTAMPTZ DEFAULT NOW()
      )
    `);
    await pool.query(
      'INSERT INTO platform_events (source,label,name,email,phone,amount,type,details) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)',
      [data.source, label, data.name||null, data.email||null, data.phone||null, data.amount||null, data.type||null, data.details||null]
    );
    console.log('[ALERTS] Calendar entry logged:', label);
  } catch(e) {
    console.warn('[ALERTS] Calendar log failed (non-blocking):', e.message);
  }
}

// ── MAIN ROUTE ─────────────────────────────────────────────────────────────
router.post('/notify', async (req, res) => {
  const data = { ...req.body, timestamp: new Date().toISOString() };
  const pool = req.app.get('db') || req.app.get('pool');
  const transporter = req.app.get('smtp') || req.app.get('transporter');

  // Fire all three in parallel — non-blocking
  const tasks = [];

  // 1. Email
  if(transporter) {
    tasks.push(
      transporter.sendMail(buildEmail(data))
        .then(() => console.log('[ALERTS] Email sent to', OWNER_EMAIL))
        .catch(e  => console.warn('[ALERTS] Email failed:', e.message))
    );
  }

  // 2. ntfy push → phone → watch
  tasks.push(sendNtfy(data));

  // 3. Calendar entry
  tasks.push(logCalendar(pool, data));

  // Return immediately — don't make the user wait
  res.json({ ok: true, queued: tasks.length });

  // Settle in background
  Promise.allSettled(tasks).then(results => {
    results.forEach((r,i) => r.status==='rejected' && console.warn('[ALERTS] task',i,'failed:',r.reason));
  });
});

// ── CALENDAR FEED — today + last 30 days ──────────────────────────────────
router.get('/events', async (req, res) => {
  const pool = req.app.get('db') || req.app.get('pool');
  if(!pool) return res.json({ ok: true, events: [] });
  try {
    const { rows } = await pool.query(
      'SELECT * FROM platform_events ORDER BY created_at DESC LIMIT 200'
    );
    res.json({ ok: true, events: rows });
  } catch(e) {
    res.json({ ok: true, events: [], error: e.message });
  }
});

// ── TODAY SUMMARY ──────────────────────────────────────────────────────────
router.get('/today', async (req, res) => {
  const pool = req.app.get('db') || req.app.get('pool');
  if(!pool) return res.json({ ok: true, count: 0 });
  try {
    const { rows } = await pool.query(
      "SELECT source, label, COUNT(*) as count FROM platform_events WHERE created_at >= CURRENT_DATE GROUP BY source, label ORDER BY count DESC"
    );
    res.json({ ok: true, today: rows });
  } catch(e) {
    res.json({ ok: true, today: [] });
  }
});

module.exports = router;
