import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

dotenv.config();

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.MAIL_USER,
    pass: process.env.MAIL_PASS,
  },
});

export async function sendReportEmail(reportName, recipient = process.env.ADMIN_EMAIL) {
  const mailOptions = {
    from: process.env.MAIL_USER,
    to: recipient,
    subject: `AuditDNA Report: ${reportName}`,
    text: `Your AuditDNA report (${reportName}) is ready.`,
    attachments: [
      {
        filename: `${reportName}.pdf`, // Assuming PDF has been generated by the frontend
        path: `./reports/${reportName}.pdf`,
      },
    ],
  };

  try {
    await transporter.sendMail(mailOptions);
    return { success: true, message: `âœ… Report emailed to ${recipient}` };
  } catch (err) {
    return { success: false, message: err.message };
  }
}

